EXPERIMENT:
  NAME: ""
  TAG: "MLKD,res110,res20"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MLKD"
  TEACHER: "resnet110"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
