EXPERIMENT:
  NAME: ""
  TAG: "MLKD,vgg13,mv2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MLKD"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
