EXPERIMENT:
  NAME: ""
  TAG: "MLKD,wrn_40_2,wrn_16_2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MLKD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
